import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 14
offset = { y = 4 }
glyph_offset = { y = 2 }

[window]
padding = { x = 10, y = 10 }

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]
