tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
brew "btop"
brew "python@3.12"
brew "cask"
brew "certifi"
brew "curl"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "grep"
brew "jq"
brew "lazygit"
brew "mas"
brew "mise"
brew "neovim"
brew "postgresql@16"
brew "pygments"
brew "ripgrep"
brew "spaceship"
brew "trash"
brew "utf8proc", args: ["HEAD"]
cask "arc"
cask "docker"
cask "firefox"
cask "font-commit-mono-nerd-font"
cask "maccy"
cask "rectangle"
cask "wezterm"
cask "zed"
mas "Color Picker", id: 1545870783
mas "Numbers", id: 409203825
