tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "romkatv/powerlevel10k"
tap "shopify/shopify"
brew "commitizen"
brew "deno"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "mas"
brew "postgresql"
brew "python@3.9"
brew "tree"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "shopify/shopify/shopify-cli"
cask "clickup"
cask "firefox"
cask "font-blex-mono-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "maccy"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "notion"
cask "slack"
cask "visual-studio-code"
mas "ColorSlurp", id: 1287239339
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
