tap "homebrew/autoupdate"
brew "awscli"
brew "btop"
brew "cask"
brew "certifi"
brew "colima"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "fd"
brew "python@3.12"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "grep"
brew "jq"
brew "lazygit"
brew "mas"
brew "mise"
brew "utf8proc", args: ["HEAD"]
brew "neovim"
brew "postgresql@16"
brew "pygments"
brew "ripgrep"
brew "starship"
brew "trash", link: true
brew "zsh"
brew "zsh-vi-mode"
cask "firefox"
cask "font-commit-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "maccy"
cask "microsoft-edge"
cask "rectangle"
cask "spotify"
cask "zen-browser"
mas "Color Picker", id: 1545870783
mas "Numbers", id: 409203825
mas "UTC Time", id: 1538245904
