set -g extended-keys on
set -g extended-keys-format csi-u

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'duo'
set -g @tmux2k-left-plugins "session cpu ram"
set -g @tmux2k-right-plugins "battery network"
set -g @tmux2k-show-powerline false

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
