set -g extended-keys on
set -g extended-keys-format csi-u

set-option -g status-position top

bind c new-window -c "#{pane_current_path}"

# Theme colors
set -g @bg_color "#000000"
set -g @active_color "#ffffff"
set -g @inactive_color "#888888"
set -g @text_color "#bbbbbb"
set -g @accent_color "#efefef"
set -g @border_color "#444444"
set-option -g status on
set-option -g status-position top
set-option -g status-interval 3
set-option -g status-justify left
set-option -g status-style "bg=#{@bg_color},fg=#{@text_color}"
set-option -g status-left-length 100
set-option -g status-right-length 100
set-option -g pane-border-style "fg=#{@border_color}"
set-option -g pane-active-border-style "fg=#{@active_color}"
set-option -g message-style "bg=#{@bg_color},fg=#{@text_color},bold"
set-option -g message-command-style "bg=#{@bg_color},fg=#{@text_color},bold"
set-option -g window-status-format "#[fg=#{@inactive_color},bg=#{@bg_color}] #I:#W "
set-option -g window-status-current-format "#[fg=#{@active_color},bg=#{@bg_color},bold] #I:#W "
set-option -g window-status-separator ""
set-option -g status-left "#[fg=#{@accent_color},bold]  #S #[fg=#{@border_color}]│ "
set-option -g status-right \
	"#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh directory #{pane_current_path}) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh cpu) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh memory) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh battery)"
set-option -g clock-mode-colour "#ffffff"
set-option -g clock-mode-style 24

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
