bind c new-window -c "#{pane_current_path}"

set -g extended-keys on
set -g extended-keys-format csi-u
set -g status-position top
# Theme colors
set -g @bg_color "#000000"
set -g @active_color "#ffffff"
set -g @inactive_color "#888888"
set -g @text_color "#bbbbbb"
set -g @accent_color "#efefef"
set -g @border_color "#444444"
set -g status on
set -g status-position top
set -g status-interval 3
set -g status-justify left
set -g status-style "bg=#{@bg_color},fg=#{@text_color}"
set -g status-left-length 100
set -g status-right-length 100
set -g pane-border-style "fg=#{@border_color}"
set -g pane-active-border-style "fg=#{@active_color}"
set -g message-style "bg=#{@bg_color},fg=#{@text_color},fill=#{@bg_color},bold"
set -g message-command-style "bg=#{@bg_color},fg=#{@text_color},fill=#{@bg_color},bold"
set -g window-status-format "#[fg=#{@inactive_color},bg=#{@bg_color}] #I:#W "
set -g window-status-current-format "#[fg=#{@active_color},bg=#{@bg_color},bold] #I:#W "
set -g window-status-separator ""
set -g status-left "#[fg=#{@accent_color},bold]  #S #[fg=#{@border_color}]│ "
set -g status-right \
	"#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh directory #{pane_current_path}) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh cpu) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh memory) #[fg=#{@border_color}]│ \
#[fg=#{@accent_color}] #[fg=#{@text_color}]#($HOME/.config/tmux/segments.sh battery)"
set -g clock-mode-colour "#ffffff"
set -g clock-mode-style 24

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
